sudo: false

language: java

jdk:
 - oraclejdk8

notifications:
 email: false

branches:
 only:
  - master
  - development

install: true

script:
- mvn clean install
- mvn -B release:clean release:prepare
